// frontend/src/components/BookCard.vue
<script setup>
import { computed } from 'vue'
import { Card, CardContent, CardFooter } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { BookOpen, Star, MoreVertical, Edit, Trash2, Heart } from 'lucide-vue-next'
import StarRating from '@/components/ui/StarRating.vue'

const props = defineProps({
  book: {
    type: Object,
    required: true,
  },
})

const emit = defineEmits(['edit', 'delete', 'view', 'toggle-favorite'])

// Status badge variants
const statusConfig = {
  want_to_read: { label: 'Want to Read', variant: 'secondary' },
  currently_reading: { label: 'Reading', variant: 'default' },
  read: { label: 'Read', variant: 'outline' },
  abandoned: { label: 'Abandoned', variant: 'destructive' },
}

const statusInfo = computed(() => statusConfig[props.book.status] || statusConfig.want_to_read)

// Cover image with fallback
const coverImage = computed(() => {
  return props.book.book?.cover_image || `https://via.placeholder.com/150x200?text=${props.book.book?.title}`
})

// Authors string
const authorsString = computed(() => {
  return props.book.book?.authors?.map((a) => a.name).join(', ') || 'Unknown Author'
})

// Reading progress percentage
const progressPercent = computed(() => {
  return props.book.reading_progress || 0
})

// No longer needed - using StarRating component
</script>

<template>
  <Card class="group hover:shadow-lg transition-all duration-200 cursor-pointer overflow-hidden">
    <!-- Book cover -->
    <div 
      class="relative aspect-[2/3] bg-muted overflow-hidden"
      @click="emit('view', book)"
    >
      <img
        :src="coverImage"
        :alt="book.book?.title"
        class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
      />
      
      <!-- Favorite heart -->
      <button
        v-if="book.is_favorite"
        class="absolute top-2 right-2 p-2 bg-white/90 rounded-full shadow-md"
        @click.stop="emit('toggle-favorite', book)"
      >
        <Heart class="w-4 h-4 text-red-500 fill-red-500" />
      </button>

      <!-- Progress bar for currently reading -->
      <div v-if="book.status === 'currently_reading' && progressPercent > 0" class="absolute bottom-0 left-0 right-0 h-1 bg-black/20">
        <div 
          class="h-full bg-primary transition-all duration-300"
          :style="{ width: `${progressPercent}%` }"
        />
      </div>
    </div>

    <CardContent class="p-4 space-y-2" @click="emit('view', book)">
      <!-- Title -->
      <h3 class="font-semibold text-sm line-clamp-2 group-hover:text-primary transition-colors">
        {{ book.book?.title }}
      </h3>

      <!-- Authors -->
      <p class="text-xs text-muted-foreground line-clamp-1">
        {{ authorsString }}
      </p>

      <!-- Status badge -->
      <Badge :variant="statusInfo.variant" class="text-xs">
        {{ statusInfo.label }}
      </Badge>

      <!-- Rating -->
      <StarRating
        v-if="book.rating"
        :model-value="book.rating"
        :size="12"
        :readonly="true"
        :show-value="true"
      />

      <!-- Progress info -->
      <div v-if="book.status === 'currently_reading'" class="text-xs text-muted-foreground">
        <div class="flex items-center gap-1">
          <BookOpen class="w-3 h-3" />
          <span>{{ book.current_page || 0 }} / {{ book.book?.pages || '?' }} pages</span>
        </div>
      </div>

      <!-- Quotes count -->
      <div v-if="book.quotes_count > 0" class="text-xs text-muted-foreground">
        {{ book.quotes_count }} {{ book.quotes_count === 1 ? 'quote' : 'quotes' }}
      </div>
    </CardContent>

    <CardFooter class="p-4 pt-0 flex justify-between items-center">
      <!-- View button -->
      <Button 
        variant="ghost" 
        size="sm"
        @click="emit('view', book)"
      >
        View Details
      </Button>

      <!-- Actions dropdown -->
      <DropdownMenu>
        <DropdownMenuTrigger as-child>
          <Button variant="ghost" size="icon" @click.stop>
            <MoreVertical class="w-4 h-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem @click="emit('edit', book)">
            <Edit class="w-4 h-4 mr-2" />
            Edit
          </DropdownMenuItem>
          <DropdownMenuItem @click="emit('toggle-favorite', book)">
            <Heart class="w-4 h-4 mr-2" />
            {{ book.is_favorite ? 'Remove from favorites' : 'Add to favorites' }}
          </DropdownMenuItem>
          <DropdownMenuItem 
            class="text-destructive focus:text-destructive"
            @click="emit('delete', book)"
          >
            <Trash2 class="w-4 h-4 mr-2" />
            Remove
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </CardFooter>
  </Card>
</template>

// frontend/lumina-library/bookdetails/BookCard.tsx

import React from 'react';
import { GoogleBook } from '../types';
import { Star, BookOpen, Calendar, Globe, ExternalLink } from 'lucide-react';

interface BookCardProps {
  book: GoogleBook;
  onClick: (book: GoogleBook) => void;
  onOpenDetail?: (book: GoogleBook) => void;
}

export const BookCard: React.FC<BookCardProps> = ({ book, onClick, onOpenDetail }) => {
  const { volumeInfo } = book;
  const title = volumeInfo.title;
  const authors = volumeInfo.authors?.join(', ') || 'Unknown Author';
  const coverUrl = volumeInfo.imageLinks?.thumbnail?.replace('http:', 'https:') || 
    `https://via.placeholder.com/300x450/1E293B/64748B?text=${encodeURIComponent(title)}`;
  
  return (
    <div 
      className="group cursor-pointer transition-all duration-300 transform hover:-translate-y-2"
      onClick={() => onClick(book)}
    >
      {/* Cover Image Container */}
      <div className="relative aspect-[2/3] w-full rounded-xl overflow-hidden shadow-2xl bg-slate-800 border border-slate-700/50">
        <img 
          src={coverUrl} 
          alt={title} 
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
          loading="lazy"
        />
        
        {/* Hover Overlay */}
        <div className="absolute inset-0 bg-slate-950/80 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col items-center justify-center p-6 text-center space-y-4">
          <div className="flex items-center gap-1.5 text-amber-400">
            <Star size={16} fill="currentColor" />
            <span className="font-semibold">{volumeInfo.averageRating || 'N/A'}</span>
          </div>
          <div className="flex flex-col items-center text-slate-300 text-sm space-y-1">
            <span className="flex items-center gap-1.5">
              <BookOpen size={14} /> {volumeInfo.pageCount || '?'} pages
            </span>
            <span className="flex items-center gap-1.5">
              <Calendar size={14} /> {volumeInfo.publishedDate?.split('-')[0] || 'Unknown'}
            </span>
          </div>
          <div className="flex flex-col gap-2 w-full">
            <button className="w-full px-5 py-2 glass rounded-full text-white text-sm font-medium hover:bg-white/20 transition-colors">
              Quick Preview
            </button>
            {onOpenDetail && (
              <button 
                onClick={(e) => { e.stopPropagation(); onOpenDetail(book); }}
                className="w-full px-5 py-2 rounded-full bg-indigo-500 text-white text-sm font-bold hover:bg-indigo-400 transition-colors flex items-center justify-center gap-2"
              >
                Full Details <ExternalLink size={14} />
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Book Info */}
      <div className="mt-4 px-1">
        <h3 className="text-slate-100 font-semibold line-clamp-2 leading-tight group-hover:text-indigo-400 transition-colors">
          {title}
        </h3>
        <p className="text-slate-400 text-sm mt-1 truncate">{authors}</p>
        
        <div className="flex flex-wrap gap-2 mt-3">
          {volumeInfo.publishedDate && (
            <span className="px-2 py-0.5 rounded bg-slate-800 text-[10px] font-bold text-slate-400 uppercase tracking-wider">
              {volumeInfo.publishedDate.split('-')[0]}
            </span>
          )}
          {volumeInfo.language && (
            <span className="px-2 py-0.5 rounded bg-slate-800 text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
              <Globe size={10} /> {volumeInfo.language.toUpperCase()}
            </span>
          )}
        </div>
      </div>
    </div>
  );
};
